{% set name = "positional" %}
{% set version = "1.1.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "14e5b502bad1bbccade474602ac773bd9d88aaf3b016985747ea992567f9597b" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
    - pbr >=1.8

  run:
    - python
    - pbr >=1.8
    - wrapt

test:
  imports:
    - positional

about:
  home: https://github.com/morganfainberg/positional
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Library to enforce positional or key-word arguments'

extra:
  recipe-maintainers:
    - pmlandwehr
    - morganfainberg
