travis:
  secure:
    BINSTAR_TOKEN: IpQKLd4+hiPu0Vb6utKsmNq6NpGq40q+0yStzEqvNhbi3TFEC47ibAVFeK1J9UVwk607bwcxrEbWlwoOYUyQMhQPfzEBpm1ZpS6A4OP5yENgf4KKjcpUFoIaixFMmRpqUX2p0WBP3BNhSd2LtMduROl58k+Jxla+I/Y0GyZwqhu+2KQbZtbC2IexdRnLSvh6tLOaK/A0LcxzhAaNMyteH5lqFKRzqD2fRu9OuLC2xt1pa9MHnoG4lR8ASbMGa/17yqdIEivp6IkhSwcf8A+R/EiHs2OCj5pQdykXHoTB2axKioGZfQhRCbNG4iuigs+MvtfqOcDD/YPwvZq0Ji3ZPcQnC5rYw3x9SFpkc3FOSE7/5LKJLD/0+UB78ki5ZKhIKFekCHJPEWMj8NwMdlbUrRtDsOeG6fDTzBehHSfzOcFESKLKkBhuEdrhSjA0m37bJv+untLHucscNWfRBCO6YMAxGr+rzgQez11XmhyAH3v106ZFqZbNck72N2BygfzntVWowMUbPz3T83T+30vuFWUJVPOlPxhtMBk82m4sI6kPB2SPMBmVNHx1pzZ7Ie4k1fYmWfiy9LOxngQ65UNBDz3IVaxxykP4JTFn+OntN1A3RPNckAupISrmXlldhQTmlYtGgd9b6lQ0T7FE313gbOb4iJWpRVgbyLay7IQb+qo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
