travis:
  secure:
    BINSTAR_TOKEN: YU/gdHOXa9iqdsa+nkeHOKIRqFMtTpvCVpCpMgTPMQ6gtptWr7yD+BOY9naADVSD82CR/RT6E8pJpxBGEaEQt45REgexNO1BzJjpeiuQYGzsP2Dc59/u7YlqjWRXSOGVj++BDNeXHrueCsizABqMC9s3IAk/4/jE64zSqIKZtkgc821tA/3X3jDSmfx1LsA6RHAb2mXWsieGMk3Mbv+aM3l/gYxegiv0gUHIu9NWhBLXvIcPqyHOuLcNeRn6kqfJC6+tZ0ikwWDJt28Cywrhh+qvp325m5Fr6HhVOcMS+M6hhV0uI3uTiMoO6ei+Yp5i/K/rbf/4YwKNi2CMwKInUqNRUktppZ4X8DU8lIHWuo3oXyV9gNmla1pAwfED0oRtRVU4Gy58YWHb3itXJ0BrpYqMVyo2z3Zdaja9Hb6NLfjU2uRZISBuuuG8J1W3mXRiHrgeadItTvca2GL9RoBYSesdBxBa9tQ+j4azGpsiKAiWRLDm2bc+vDRo9MEMICBGFVT/R9hNw2zN903LJT3NNzP3Xd0wd3JQPy+heqqR0B3FNY1WBUQTMMHYVeL5g4SdGWUWI785OhDEkQLtzGK8RPOC7SyrcqHOlPKiuj3TqQwt/4fxnWeKnL4HREVa/NXpT9t5smWOEkYeWQcqUSog+LXzuUh6LNrBg7hXSVpsfqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
